### PR TITLE
Removed symfony full stack dependency

### PR DESCRIPTION
**Pull request by core23**
I am targetting this branch, because this is only a slight BC break.

## Changelog

```markdown
### Changed
 - replaced full stack symfony dependencies with only used ones.

### Removed
 - removed `symfony/symfony` dependency
```

## Subject

We don't need everything from symfony. Only the following classes are used:

```
use Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Bundle\FrameworkBundle\Templating\EngineInterface;
use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;
use Symfony\Component\Config\Definition\Processor;
use Symfony\Component\Config\FileLocator;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Definition;
use Symfony\Component\DependencyInjection\Loader\XmlFileLoader;
use Symfony\Component\DependencyInjection\Reference;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormFactoryInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Bundle\Bundle;
use Symfony\Component\HttpKernel\DependencyInjection\Extension;
use Symfony\Component\HttpKernel\Exception\HttpException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\Routing\RouterInterface;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Symfony\Component\Templating\EngineInterface;
```

### CODE REVIEW

**Comment by greg0ire** [comment]
Jesus…

**Comment by OskarStark** [comment]
> Jesus…

Here I am, whats up? 🤣

**Comment by OskarStark** [comment]
minor or patch?

**Comment by greg0ire** [comment]
> Here I am, whats up? :rofl:

Guys he's back! Knew it!

**Comment by core23** [comment]
It's a `minor` change for me, because this is no bug and has a tiny BC.

**Comment by OskarStark** [comment]
Thank you @core23 👍

**Comment by greg0ire** [comment]
> It's a minor change for me, because this is no bug and has a tiny BC break.

I'm a bit unsure about this, be if you both agree together then fine.

**Pull request merged**
