### PR TITLE
added sonata.news.admin.groupname parameter to admin config

### PR DESCRIPTION
**Pull request by tamayg**

### CODE REVIEW

**Comment by sagikazarmark** [comment]
:+1:

**Comment by OskarStark** [comment]
IMO we don't need this additional parameter

**Comment by sagikazarmark** [comment]
I think it should be consistent across different projects. If one has, other should as well. Or a decision should be made to remove it from everywhere, but that's a BC break, so can only be removed in a major version.

**Comment by OskarStark** [comment]
hmm, thats true @sagikazarmark i absolutetly agree that this should be consitenst.

I think we should the create a ticket with a tasklist to achive this across all bundles and create separate PR's

what do you guys think @sagikazarmark @rande @Soullivaneuh  ?

**Comment by sagikazarmark** [comment]
Good idea. Actually, I offered my help in sonata-project/sandbox#548 if you have such roadmap, I am here to help. Other things that should be made consistent across projects: install instructions (for example easy extends: one place it is at the beginning, another it is at the end).

**Comment by OskarStark** [comment]
ok can you then please create a ticket to make the admin group name consistent?

Please create the ticket in the SonataAdminBundle and add a tasklist an refer to the PR's

**Comment by core23** [comment]
Please rebase @tamayg

**Comment by core23** [comment]
This PR is against an outdated branch. Please close this and create a new one against the latest master branch @tamayg

**Pull request closed without merging**
