### PR TITLE
Improved extensibility of controller actions

### PR DESCRIPTION
**Pull request by core23**
I am targetting this branch, because this is a BC break.

## Changelog

``` markdown
### Added
- Added `$request` parameter to all controller actions
```
## Subject

Improved extensibility of controller actions by injection the `$request` parameter by default.

### CODE REVIEW

**Comment by core23** [comment]
> Not sure this is useful, see https://3v4l.org/ULUpv I can extend the controller and have a different signature as long as I make it compatible with the parent signature (by adding `= null`)

PHP sometimes does strange things Oo Didn't know that.

The original idea was to add the parameter by default, so every extension could use the `request` when overriding the parent method.

**Comment by greg0ire** [comment]
> PHP sometimes does strange things Oo Didn't know that.

When you try a different signature, you don't get an error message saying it is different, you get one saying it is incompatible. Compatible means you can use the method just like you would use it in the parent. So in my example, you can use `$b->action('id')`, because `$request` is optional, which means the signature is compatible :)
Not sure how Symfony behaves when you put that `= null` but technically, you already can have a `$request` parameter.

**Comment by opichon** [comment]
Indeed, the suggestion by @greg0ire works. At least this is a solution in case the MR is not accepted. As to the MR itself, I suppose this is a matter of opinion. For our own code, our policy is to add Request $request to all actions; especially so for bundles designed as open-source code, therefore very likely to be extended. 

Issues arise whenever the original method is changed to use the request, in which case the extending class becomes incompatible. Of course, that's par for the course, but niggling irritations can easily be avoided by systematically adding Request $request as the first parameter.

**Comment by greg0ire** [comment]
> Issues arise whenever the original method is changed to use the request, in which case the extending class becomes incompatible.

It might become incompatible if you add the request argument in another position, but if you don't, here is what happens : https://3v4l.org/bKmZs

So IMO, I think we should reduce the BC-breaks to the methods that really need this `$request` argument.

**Comment by opichon** [comment]
Sure, this is your call. I now have a working solution anyway thanks to @greg0ire .

**Pull request closed without merging**
