### PR TITLE
fix regression on archive page

### PR DESCRIPTION
**Pull request by rlamarche**

### CODE REVIEW

**Comment by OskarStark** [comment]
This Looks wrong to me 

Ping @core23 

Maybe related to #271 ?

**Comment by rlamarche** [comment]
I don't really know, I think that b677cff6056574c550a13658de1ce484cdb9edc3 introduced the regression, on line 76 in PostController

**Comment by core23** [comment]
@OskarStark Looks wrong, but is right in this case. To keep this BC we should apply this PR as we are passing a parameter to a method that has an optional parameter but isn't required for an override.

**Comment by OskarStark** [comment]
Thank you @rlamarche and @core23

**Comment by rlamarche** [comment]
You're welcome, your bundles are awesome :-)
Thank you for providing them !

**Comment by OskarStark** [comment]
Thank you @rlamarche :+1:

**Pull request merged**
