### PR TITLE
Fix error when showing year archive

### LINKED ISSUE #216: FatalErrorException: call protected method PostManager::getPublicationDateQueryParts()
Hello!

I was trying to create a template with some months listed in a column, to access posts. But when I call in twig:
```twig
{{ url('sonata_news_archive_monthly', {'year':'2014', 'month': '9'} ) }}">
```

It returns:
```
FatalErrorException: Error: Call to protected method Sonata\NewsBundle\Entity\PostManager::getPublicationDateQueryParts() from context 'Sonata\NewsBundle\Controller\PostController' in /var/www/.../vendor/sonata-project/news-bundle/Controller/PostController.php line 131
```

Could you update the ``getPublicationDateQueryParts`` method to public?

### PR DESCRIPTION
**Pull request by core23**
There is an error when showing the yearly or mothly archive.

This should fix #216

### CODE REVIEW

**Comment by core23** [comment]
@rande ping

**Comment by core23** [comment]
Please merge, because the archive won't work

**Comment by Soullivaneuh** [comment]
Hello @core23, could you please rebase your PR and write some tests to reproduce the error?

Thanks.

**Comment by core23** [comment]
@Soullivaneuh done :)

**Comment by Soullivaneuh** [comment]
Please rename your commit: "Fix error when showing year archive".

Also, can you give me a concrete case to reproduce the error?

**Comment by core23** [comment]
Just visit the year archive on the blog ;)
http://demo.sonata-project.org/blog/2015/

**Comment by rande** [comment]
;)

**Pull request merged**
