### PR TITLE
Closing API by marking some classes with "@final" annotation

### PR DESCRIPTION
**Pull request by wbloszyk**
## Subject

Closing API by marking some classes with "@Final" annotation.

I am targeting this branch, because these changes respect BC.

## Changelog

```markdown
### Deprecated
- `Sonata\NewsBundle\Controller\PostController`
- Extending classes marked as final:
 * `Sonata\NewsBundle\Block\Breadcrumb\NewsArchiveBreadcrumbBlockService`
 * `Sonata\NewsBundle\Block\Breadcrumb\NewsPostBreadcrumbBlockService`
 * `Sonata\NewsBundle\Block\RecentCommentsBlockService`
 * `Sonata\NewsBundle\Block\RecentPostsBlockService`
 * `Sonata\NewsBundle\Command\SynchronizeCommentsCountCommand`
 * `Sonata\NewsBundle\DependencyInjection\Configuration`
 * `Sonata\NewsBundle\DependencyInjection\SonataNewsExtension`
 * `Sonata\NewsBundle\Entity\CommentManager`
 * `Sonata\NewsBundle\Entity\PostManager`
 * `Sonata\NewsBundle\Exception\NoDriverException`
 * `Sonata\NewsBundle\Form\Type\CommentStatusType`
 * `Sonata\NewsBundle\Form\Type\CommentType`
 * `Sonata\NewsBundle\Mailer\Mailer`
 * `Sonata\NewsBundle\Permalink\CollectionPermalink`
 * `Sonata\NewsBundle\Permalink\DatePermalink`
 * `Sonata\NewsBundle\Status\CommentStatusRenderer`
 * `Sonata\NewsBundle\Twig\Extension\NewsExtension`
 * `Sonata\NewsBundle\Util\HashGenerator`
 * `Sonata\NewsBundle\SonataNewsBundle`
```

### CODE REVIEW

**Review by VincentLanglet — COMMENTED** [review]
We just marked this bundle as abandoned 
https://github.com/sonata-project/dev-kit/issues/1669

Not sure the benefit of this since we were not planning doing another major.

**Comment by wbloszyk** [comment]
i want to keep this bundle up to date. It will be easy to update it, becouse it has not mamy third part dependencies. Also current dependencies will be reduce.

**Review by VincentLanglet — APPROVED** [review]

**Comment by VincentLanglet** [comment]
> i want to keep this bundle up to date. It will be easy to update it, becouse it has not mamy third part dependencies. Also current dependencies will be reduce.

Then maybe it's not needed to mark this one as "abandoned" ^^' @sonata-project/contributors

**Comment by jordisala1991** [comment]
There is no usage of this bundle, and no one asked for support since we opened the issue. Why dont we focus our efforts on bundles that people use? If you want to maintain it, fine by me, but to me there are a lot of sonata bundles needing work.

**Comment by VincentLanglet** [comment]
> There is no usage of this bundle, and no one asked for support since we opened the issue. Why dont we focus our efforts on bundles that people use? If you want to maintain it, fine by me, but to me there are a lot of sonata bundles needing work.

I agree it could be better for the sonata ecosystem to do something else,
but if he needs it for any reason and want to maintain it, we have no reason to block this PR

**Review by jordisala1991 — APPROVED** [review]

**Comment by wbloszyk** [comment]
> > There is no usage of this bundle, and no one asked for support since we opened the issue. Why dont we focus our efforts on bundles that people use? If you want to maintain it, fine by me, but to me there are a lot of sonata bundles needing work.
> 
> I agree it could be better for the sonata ecosystem to do something else,
> but if he needs it for any reason and want to maintain it, we have no reason to block this PR

#777

**Review by phansys — APPROVED** [review]

**Comment by phansys** [comment]
Thank you @wbloszyk!

**Pull request merged**
