### PR TITLE
3.13.0

### PR DESCRIPTION
**Pull request by greg0ire**

### CODE REVIEW

**Comment by core23** [comment]
Shouldn't we wait for https://github.com/sonata-project/SonataNewsBundle/pull/605 ?

**Comment by greg0ire** [comment]
@wbloszyk asked me privately to do this release… :confused:

**Comment by wbloszyk** [comment]
Yes, it should be merge too. I working on it all day and cant find issue. Mybe you can help?

**Comment by jordisala1991** [comment]
Try to upgrade symfony to 4.4 @wbloszyk

**Comment by wbloszyk** [comment]
I done it https://github.com/sonata-project/SonataNewsBundle/pull/605. I realized I should move checking to CompilerPassTest, not ExtensionTest. :)

**Comment by jordisala1991** [comment]
I think now you can update the release with latest pr and we are good to go @greg0ire

**Pull request merged**
