### PR TITLE
Use more specific PHPDoc

### PR DESCRIPTION
**Pull request by core23**
## Subject

I am targeting this branch, because this is BC.

## Changelog

```markdown
### Changed
- Match PHPDoc with doctrine model 

### Removed
- Remove superfluous PHPDoc 
```

### CODE REVIEW

**Comment by OskarStark** [comment]
Thanks @core23

**Comment by greg0ire** [comment]
Why would this be patch and not pedantic?

**Comment by core23** [comment]
> Why would this be patch and not pedantic?

AFAIK PHPDoc signature changes were `patch`es

**Comment by greg0ire** [comment]
`patches` for IDE autocompletion/SA tools? Should this be patch then: https://github.com/sonata-project/sonata-doctrine-extensions/pull/134 ?

**Comment by core23** [comment]
> `patches` for IDE autocompletion/SA tools? 
Yes, we should tag those at least as a patch, because this could have an impact on your QA tools

> Should this be patch then: [sonata-project/sonata-doctrine-extensions#134](https://github.com/sonata-project/sonata-doctrine-extensions/pull/134) ?

https://github.com/sonata-project/sonata-doctrine-extensions/pull/134#issuecomment-516111668

**Comment by greg0ire** [comment]
This last comment is not about the phpdoc change, and I already answered that: https://github.com/sonata-project/sonata-doctrine-extensions/pull/134#issuecomment-516117323

**Pull request merged**
