### PR TITLE
Support Symfony 3

### PR DESCRIPTION
**Pull request by 0x2f8f**
I am targetting this branch, because need Support Symfony 3.

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
This bundle can not support Symfony 3 yet because of `user-bundle`.

**Comment by zapashcanon** [comment]
@Soullivaneuh I looked at user-bundle, and didn't find any issue/PR giving informations about the SF3 compatibility state, do you know where I could find this ?

**Comment by core23** [comment]
https://github.com/sonata-project/SonataUserBundle/issues/322

**Comment by Soullivaneuh** [comment]
@zapashcanon In a nutshell, the last **stable** version of FOSUser, required by SonataUser does not support Symfony 3.

So SonataUser can't support it either, neither NewsBundle.

**Comment by zapashcanon** [comment]
Thx. The master branch seems to work well with SF3, hoping the next release/tag will be here soon then. :)

**Comment by Soullivaneuh** [comment]
> hoping the next release/tag will be here soon then. :)

Honestly, it depends a lot of the FOSUserBundle 2.0 stable release.

**Comment by zapashcanon** [comment]
Yep' I was talking about the FOSUserBundle one, I saw some PR you opened there. ;)

**Pull request closed without merging**
